In [8]:
import pandas as pd
import numpy as np

def create_time_series_windows(data, window_size, horizon=1):
    """
    Creates windows from the time series data.
    
    :param data: The time series data as a pandas DataFrame or Series.
    :param window_size: The size of the windows.
    :param horizon: The horizon (number of time steps to predict).
    :return: A tuple (X, y) where X is the input windows and y is the output windows.
    """
    X, y = [], []
    for i in range(len(data) - window_size - horizon + 1):
        X.append(data[i:i+window_size])
        y.append(data[i+window_size:i+window_size+horizon])
    return np.array(X), np.array(y)

# Sample DataFrame
df = pd.DataFrame({'value': np.sin(np.linspace(0, 50, 200))})
window_size = 3
X, y = create_time_series_windows(df['value'].values, window_size)

In [9]:
df

value
0    0.000000
1    0.248621
2    0.481629
3    0.684392
4    0.844175
..        ...
195 -0.955251
196 -0.851716
197 -0.694694
198 -0.494047
199 -0.262375

[200 rows x 1 columns]

In [10]:
print(X)


[[ 0.          0.24862099  0.481629  ]
 [ 0.24862099  0.481629    0.68439153]
 [ 0.481629    0.68439153  0.84417544]
 [ 0.68439153  0.84417544  0.95094655]
 [ 0.84417544  0.95094655  0.99799984]
 [ 0.95094655  0.99799984  0.98238043]
 [ 0.99799984  0.98238043  0.90506919]
 [ 0.98238043  0.90506919  0.77092115]
 [ 0.90506919  0.77092115  0.58836056]
 [ 0.77092115  0.58836056  0.36885193]
 [ 0.58836056  0.36885193  0.12618003]
 [ 0.36885193  0.12618003 -0.12441577]
 [ 0.12618003 -0.12441577 -0.36719847]
 [-0.12441577 -0.36719847 -0.58692173]
 [-0.36719847 -0.58692173 -0.7697873 ]
 [-0.58692173 -0.7697873  -0.90431153]
 [-0.7697873  -0.90431153 -0.98204653]
 [-0.90431153 -0.98204653 -0.99811068]
 [-0.98204653 -0.99811068 -0.95149517]
 [-0.99811068 -0.95149517 -0.84512737]
 [-0.95149517 -0.84512737 -0.68568702]
 [-0.84512737 -0.68568702 -0.48318668]
 [-0.68568702 -0.48318668 -0.25034303]
 [-0.48318668 -0.25034303 -0.00177827]
 [-0.25034303 -0.00177827  0.24689816]
 [-0.00177827  0.24689816

In [11]:
print(y)

[[ 0.68439153]
 [ 0.84417544]
 [ 0.95094655]
 [ 0.99799984]
 [ 0.98238043]
 [ 0.90506919]
 [ 0.77092115]
 [ 0.58836056]
 [ 0.36885193]
 [ 0.12618003]
 [-0.12441577]
 [-0.36719847]
 [-0.58692173]
 [-0.7697873 ]
 [-0.90431153]
 [-0.98204653]
 [-0.99811068]
 [-0.95149517]
 [-0.84512737]
 [-0.68568702]
 [-0.48318668]
 [-0.25034303]
 [-0.00177827]
 [ 0.24689816]
 [ 0.48006981]
 [ 0.68309389]
 [ 0.84322083]
 [ 0.95039493]
 [ 0.99788585]
 [ 0.98271122]
 [ 0.905824  ]
 [ 0.77205257]
 [ 0.58979754]
 [ 0.37050423]
 [ 0.12794389]
 [-0.12265112]
 [-0.36554384]
 [-0.58548103]
 [-0.76865101]
 [-0.903551  ]
 [-0.98170953]
 [-0.99821836]
 [-0.95204077]
 [-0.84607664]
 [-0.68698033]
 [-0.48474282]
 [-0.25206428]
 [-0.00355654]
 [ 0.24517455]
 [ 0.4785091 ]
 [ 0.68179408]
 [ 0.84226356]
 [ 0.94984031]
 [ 0.9977687 ]
 [ 0.9830389 ]
 [ 0.90657594]
 [ 0.77318154]
 [ 0.59123265]
 [ 0.37215536]
 [ 0.12970734]
 [-0.12088608]
 [-0.36388806]
 [-0.58403849]
 [-0.76751229]
 [-0.90278762]
 [-0.98136942]
 [-0.99832